# To learn more about how to use Nix to configure your environment
# see: https://developers.google.com/idx/guides/customize-idx-env
{ pkgs, ... }:

let
  # Nginx config remains the same
  fixedPortNginxConfig = pkgs.writeText "nginx-fixed-port-doh.conf" ''
    # ... (nginx config as before) ...
    error_log /dev/stdout info; 
    pid /tmp/nginx.pid;
    user nobody; 

    events {
      worker_connections 1024;
    }

    http {
      access_log /dev/stdout;
      include       ${pkgs.nginx}/conf/mime.types; 
      default_type  application/octet-stream;

      server {
        listen 8080; 
        listen [::]:8080;
        server_name localhost;

        location /dns-query {
          proxy_pass http://localhost:4000/dns-query; 
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_http_version 1.1;
          proxy_request_buffering off;
        }

        location / {
          deny all;
        }
      }
    }
  '';

  # UPDATED Blocky configuration for new format (v0.23 compatible)
  minimalBlockyConfig = pkgs.writeText "blocky-minimal.yml" ''
    ports:
      dns: 0 
      http: "0.0.0.0:4000"

    upstreams:
      groups:
        default: 
          # For plain IP addresses, Blocky defaults to UDP/TCP.
          # The 'host:' key is not used here; the value is the upstream definition.
          - 1.1.1.1
          - 8.8.8.8
          # If you wanted to specify a type, it's part of the string:
          # - "tls://1.1.1.1"
          # - "https://dns.google/dns-query"
    
    prometheus:
      enable: false

    log:
      level: info 
      format: text
  '';


in
{
  channel = "stable-24.05"; # Consider "unstable" for newer Blocky if needed

  packages = [
    pkgs.nginx
    pkgs.gettext 
    pkgs.blocky
    pkgs.curl
    pkgs.jq # For pretty-printing JSON responses from DoH
  ];

  # ... (rest of dev.nix, idx, workspace, onCreate, onStart as before) ...
  env = {};

  idx = {
    extensions = [];
    previews = {
      enable = false; 
    };

    workspace = {
      onCreate = {
        setup_environment_info = ''
          echo "--------------------------------------------------------------------"
          echo "NGINX DOH SERVER & BLOCKY SETUP INFO (Blocky Config Updated)"
          echo "--------------------------------------------------------------------"
          echo "Previews are currently DISABLED in .idx/dev.nix."
          echo ""
          echo "1. BLOCKY (DNS Resolver):"
          echo "   Blocky configuration (updated format) is defined in dev.nix."
          echo "   Path to Blocky config: ${minimalBlockyConfig}"
          echo "   Blocky will attempt to start automatically when the workspace starts (see onStart)."
          echo "   It will serve DoH on http://localhost:4000/dns-query"
          echo ""
          echo "2. FIXED-PORT NGINX DOH PROXY (generated by dev.nix):"
          echo "   Nginx is configured for a DoH proxy listening on fixed port 8080."
          echo "   It proxies /dns-query to Blocky on http://localhost:4000/dns-query."
          echo "   Path to Nginx config: ${fixedPortNginxConfig}"
          echo "   To run Nginx manually with this DoH config:"
          echo "     nginx -g 'daemon off;' -c ${fixedPortNginxConfig}"
          echo ""
          echo "TESTING DOH (RFC8484 - after starting Nginx manually and Blocky via onStart):"
          echo "   Use a proper DoH client or construct a query with the 'dns' parameter."
          echo "   Example with a simple base64url encoded query for 'example.com A':"
          echo "     DNS_QUERY_MSG=\$(printf '\\x00\\x01\\x01\\x00\\x00\\x01\\x00\\x00\\x00\\x00\\x00\\x00\\x07example\\x03com\\x00\\x00\\x01\\x00\\x01' | base64 | tr -- '+/' '-_' | tr -d '=')"
          echo "     curl -v 'http://localhost:8080/dns-query?dns='\$DNS_QUERY_MSG -H 'accept: application/dns-message' | od -t x1 -A n"
          echo "   For JSON output (if Blocky supports it for RFC8484, less common for /dns-query):"
          echo "     curl -v 'http://localhost:8080/dns-query?dns='\$DNS_QUERY_MSG -H 'accept: application/dns-json'"
          echo "--------------------------------------------------------------------"
          
          echo "Setup info complete."
        '';
        default.openFiles = [ 
          ".idx/dev.nix"
          "README.md"
        ];
      };
      onStart = {
        # Minimal setup to start Blocky in the background
        # Script 1: Start Blocky
        start_blocky_background = ''
          echo "[onStart:Blocky] === Attempting to start Blocky ==="
          echo "[onStart:Blocky] Killing existing Blocky processes..."
          ${pkgs.procps}/bin/pkill -f "${pkgs.blocky}/bin/blocky" || echo "[onStart:Blocky] No Blocky process found to kill."
          sleep 1 # Give it a moment to die
          
          echo "[onStart:Blocky] Starting new Blocky instance..."
          ${pkgs.blocky}/bin/blocky --config ${minimalBlockyConfig} > /tmp/blocky.log 2>&1 &
          BLOCKY_PID=$! # Capture PID
          
          sleep 2 # Brief wait for Blocky to initialize
          if ${pkgs.procps}/bin/pgrep -P $BLOCKY_PID > /dev/null; then
            echo "[onStart:Blocky] Blocky (PID $BLOCKY_PID) started successfully. Logs at /tmp/blocky.log"
            echo "[onStart:Blocky] Initial Blocky logs:"
            head -n 15 /tmp/blocky.log
          else
            echo "[onStart:Blocky] ERROR: Blocky failed to start. Check /tmp/blocky.log for errors."
            cat /tmp/blocky.log
          fi
          echo "[onStart:Blocky] === Blocky startup attempt finished ==="
        '';

        # Script 2: Start Nginx
        start_nginx_background =  ''
          echo "[onStart:Nginx] === Attempting to start Nginx ==="
          echo "[onStart:Nginx] Killing existing onStart Nginx processes..."
          ${pkgs.procps}/bin/pkill -f "nginx.*nginx-onstart.pid" || echo "[onStart:Nginx] No onStart Nginx process found to kill."
          sleep 1

          echo "[onStart:Nginx] Starting Nginx instance..."
          ${pkgs.nginx}/bin/nginx -g 'daemon off;' -c ${fixedPortNginxConfig} > /tmp/nginx-onstart.log 2>&1 &
          NGINX_PID=$! # Capture PID
          
          sleep 2 # Brief wait for Nginx to initialize
          if ${pkgs.procps}/bin/pgrep -P $NGINX_PID > /dev/null; then
            echo "[onStart:Nginx] Nginx (PID $NGINX_PID) started successfully. Logs at /tmp/nginx-onstart.log"
            echo "[onStart:Nginx] Initial Nginx logs:"
            head -n 15 /tmp/nginx-onstart.log
          else
            echo "[onStart:Nginx] ERROR: Nginx failed to start. Check /tmp/nginx-onstart.log for errors."
            cat /tmp/nginx-onstart.log
          fi
          echo "[onStart:Nginx] === Nginx startup attempt finished ==="
         '';

        # Script 3: Test DoH via Nginx
        test_doh_via_nginx =  ''
          echo "[onStart:Test] === Starting DoH Test via Nginx ==="
          echo "[onStart:Test] Waiting 5 seconds for services to fully initialize before testing..."
          # This sleep is important because Blocky and Nginx start concurrently with this script.
          sleep 5 

          # Verify Blocky is running (simple check, assumes it's needed for the test)
          if ! ${pkgs.procps}/bin/pgrep -f "${pkgs.blocky}/bin/blocky" > /dev/null; then
            echo "[onStart:Test] Prerequisite FAIL: Blocky process not found. Aborting test."
            echo "[onStart:Test] Check /tmp/blocky.log"
            exit 1 # Or return 1, depending on how IDX handles script failures
          fi

          # Verify Nginx is running (simple check)
          if ! ${pkgs.procps}/bin/pgrep -f "nginx" > /dev/null; then
            echo "[onStart:Test] Prerequisite FAIL: Nginx (onStart instance) process not found. Aborting test."
            echo "[onStart:Test] Check /tmp/nginx-onstart.log"
            exit 1 
          fi

          echo "[onStart:Test] Preparing RFC8484 DoH test query for example.com (A record)..."
          DNS_QUERY_HEX="000101000001000000000000076578616d706c6503636f6d0000010001"
          DNS_QUERY_MSG=$(${pkgs.coreutils}/bin/echo -n $DNS_QUERY_HEX | ${pkgs.xxd}/bin/xxd -r -p | ${pkgs.coreutils}/bin/base64 | ${pkgs.coreutils}/bin/tr -- '+/' '-_' | ${pkgs.coreutils}/bin/tr -d '=')
          
          if [ -z "$DNS_QUERY_MSG" ]; then
            echo "[onStart:Test] ERROR: Failed to generate DNS_QUERY_MSG."
            exit 1
          fi
          echo "[onStart:Test] Generated DNS_QUERY_MSG: $DNS_QUERY_MSG"
          
          echo "[onStart:Test] Executing DoH test query against http://localhost:8080/dns-query..."
          HTTP_STATUS=$(${pkgs.curl}/bin/curl -s -o /tmp/doh_test_response.bin -w "%{http_code}" "http://localhost:8080/dns-query?dns=$DNS_QUERY_MSG" -H 'accept: application/dns-message')

          echo "[onStart:Test] DoH Test HTTP Status Code: $HTTP_STATUS"
          if [ "$HTTP_STATUS" = "200" ]; then
            echo "[onStart:Test] SUCCESS: DoH query returned HTTP 200 OK."
            echo "[onStart:Test] Response (first 100 bytes, hex) from /tmp/doh_test_response.bin:"
            ${pkgs.coreutils}/bin/head -c 100 /tmp/doh_test_response.bin | ${pkgs.xxd}/bin/xxd -g 1 -u
          elif [ "$HTTP_STATUS" = "000" ]; then
            echo "[onStart:Test] FAILURE: DoH query failed. Curl could not connect (status 000)."
            echo "[onStart:Test] Ensure Nginx is listening on 8080 and Blocky on 4000."
          else
            echo "[onStart:Test] FAILURE: DoH query returned HTTP $HTTP_STATUS."
            echo "[onStart:Test] Response body (if any) from /tmp/doh_test_response.bin:"
            cat /tmp/doh_test_response.bin
          fi
          echo "[onStart:Test] === DoH Test via Nginx Finished ==="
         '';       
      };
    };
  };
}
