# To learn more about how to use Nix to configure your environment
# see: https://developers.google.com/idx/guides/customize-idx-env
{ pkgs, ... }:

let
  # Nginx configuration with a FIXED port, generated directly by Nix.
  # No 'envsubst' placeholders are needed for the port in this specific string.
  fixedPortNginxConfig = pkgs.writeText "nginx-fixed-port.conf" ''
    # Global error log to stdout.
    error_log /dev/stdout info; 
    pid /tmp/nginx.pid;
    user nobody; 

    events {
      worker_connections 1024;
    }

    http {
      access_log /dev/stdout;
      # ${pkgs.nginx} is a Nix variable, its path is interpolated here by Nix.
      include       ${pkgs.nginx}/conf/mime.types; 
      default_type  application/octet-stream;

      server {
        # Using a fixed port, e.g., 8080.
        # This config is ready to use directly without envsubst for the port.
        listen 8080; 
        listen [::]:8080; # For IPv6 compatibility on the same fixed port

        server_name localhost;

        # Files will be served from /home/user/www
        root /home/user/www; 
        index index.html index.htm;

        # Standard file serving logic. $uri is an Nginx variable.
        location / {
          try_files $uri $uri/ =404;
        }
      }
    }
  '';
in
{
  channel = "stable-24.05";

  packages = [
    pkgs.nginx
    # gettext is still useful if you use the separate dynamic template file.
    pkgs.gettext 
  ];

  env = {}; # General workspace environment variables

  idx = {
    extensions = [
      # "fivethree.vscode-nginx-conf-hint" # Helpful for editing Nginx conf
    ];

    previews = {
      # Previews are DISABLED
      enable = false; 
      # The 'previews' block below is effectively ignored.
      # previews = {
      #   web = { 
      #     command = [ "/bin/sh", "-c", "..." ]; # Would need adjustment if re-enabled
      #     manager = "web"; 
      #   };
      # };
    };

    workspace = {
      onCreate = {
        setup_nginx_environment_info = ''
          echo "--------------------------------------------------------------------"
          echo "NGINX ENVIRONMENT SETUP INFO"
          echo "--------------------------------------------------------------------"
          echo "Previews are currently DISABLED in .idx/dev.nix."
          echo ""
          echo "1. FIXED-PORT NGINX CONFIG (generated by dev.nix):"
          echo "   A ready-to-use Nginx configuration listening on a fixed port (e.g., 8080)"
          echo "   has been generated by Nix. Its path is:"
          echo "     ${fixedPortNginxConfig}"
          echo "   To run Nginx manually with this fixed-port config:"
          echo "     nginx -g 'daemon off;' -c ${fixedPortNginxConfig}"
          echo ""
          echo "2. DYNAMIC-PORT NGINX (using a separate template file):"
          echo "   If you need Nginx to listen on a port set by an environment variable,"
          echo "   you should use a separate template file (e.g., 'nginx.dynamic-port.conf.template')"
          echo "   that contains a placeholder like ''${PORT}'."
          echo "   See instructions for creating and using such a file."
          echo "--------------------------------------------------------------------"

          echo "Setting up Nginx web root directory /home/user/www..."
          mkdir -p /home/user/www
          # Create a sample index.html for testing
          echo '<!DOCTYPE html><html><head><title>Nginx on IDX (Manual Start)</title><style>body{font-family: sans-serif; display: flex; justify-content: center; align-items: center; height: 90vh; flex-direction: column;}</style></head>' > /home/user/www/index.html
          echo '<body><h1>Nginx (Manually Started)</h1><p>If Nginx is running (e.g., using the fixed-port config on port 8080), you should see this page.</p><p>Serving from <code>/home/user/www/index.html</code>.</p></body></html>' >> /home/user/www/index.html
          echo "Nginx setup info complete."
        '';
        default.openFiles = [ 
          ".idx/dev.nix"
          "README.md"
        ];
      };
      onStart = {}; # Hook for commands to run every time the workspace (re)starts
    };
  };
}
